
// ACCOUNT ACTIONS
export const USER_IS_LOGGEDIN = "USER_IS_LOGGEDIN";
export const GET_USER = "GET_USER";
export const GET_LOGGED_USER = "GET_LOGGED_USER";
export const LOGOUT = "LOGOUT";

// RECIPES ACTIONS
export const GET_ALL_RECIPES = "GET_ALL_RECIPES";
export const GET_RECIPE = "GET_RECIPE";
